# Generated by Django 2.0.6 on 2018-06-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle_app', '0003_translate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='dscription',
        ),
    ]
