# Generated by Django 2.0.6 on 2018-06-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle_app', '0006_translate_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translate',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='translate',
            name='sentence',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
